# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: 'resourceGroupName'
    displayName: "Name of the resourcegroup"
    type: string
    default: "rg"

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    connectedServiceName: 'Azure for Students(4152d77a-784e-4df1-bd82-0e04268e7073)'
    location: 'eastus2'
    resourceGroupName: 'resourceGroupName'
    csmFile: biceptemp.bicep
    